[env:vfddriver]

; baremetal avrxmega3
platform = atmelmegaavr
board = ATtiny414

; use custom updi tool to flash
upload_command = updiprog -d tiny41x -c $UPLOAD_PORT -b $UPLOAD_SPEED -e -w $SOURCE
;upload_command = pymcuprog -d attiny414 -t uart -u $UPLOAD_PORT -c $UPLOAD_SPEED write -f $SOURCE --verify -v info

; running at full speed, 20 MHz
board_build.f_cpu = 20000000L
