[env:vfddriver]

; baremetal avrxmega3
platform = atmelmegaavr
board = ATtiny414

; use updiprog to flash (https://semjonov.de/docs/tips/avr/#updi-programmer)
upload_command = updiprog -d tiny41x -c $UPLOAD_PORT -b $UPLOAD_SPEED -e -w $SOURCE